version: "3"

services:

  # バックエンドサーバ(rails)
  backend:
    #
    # コンテナ名
    container_name: backend
    # build
    build:
      context: .
      dockerfile: ./Dockerfile
    # コンテナの中に入る
    tty: true
    # 他のコンテナ起動後に起動するように制御
    depends_on:
      - db
    # ボリューム
    volumes:
      - ".:/backend"
    # WORKDIR
    working_dir: /backend
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: "development"
      DATABASE_HOST: "db"
      DATABASE_NAME: "sample_db"
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_PORT: 3306
    # ポート開放
    ports:
      - 3000:3000
    command: /bin/bash /docker-entrypoint.sh

  # DBサーバ
  db:
    # コンテナ名
    container_name: db
    # image
    image: mysql:8.0.28
    # 環境設定
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_PASSWORD: password
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - mysql_data:/var/lib/mysql
    # ポート開放
    ports:
      - 3306:3306

# 名前付きボリュームをdockerホストの管理下で作成
volumes:
  # postgresqk
  mysql_data: {}
